FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .

RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir -r requirements.txt

COPY weather_service.py .

CMD ["uvicorn", "weather_service:app", "--host", "0.0.0.0", "--port", "8001"]